name: Bump version and publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: true

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn --immutable

      - name: Setup Git
        run: |
          git config user.name 'Jason Yu'
          git config user.email 'me@ycmjason.com'

      - name: bump version
        run: yarn workspaces foreach version ${{ github.event.inputs.version }}

      - name: Build
        run: yarn build

      - name: Commit and create git tag
        run: |
          VERSION=`node -p "require('./package.json').version"`
          git commit -am "Version: $VERSION"
          git tag -a $VERSION -m "Version $VERSION"

      - name: Push latest version
        run: git push origin main --tags

      - name: NPM Publish
        run: |
          yarn config set --home 'npmRegistries["https://registry.yarnpkg.com"].npmAuthToken' "${{ secrets.NPM_TOKEN }}"
          yarn workspaces foreach --no-private npm publish
